#!/bin/env bash
# Check if all 4 required parameters are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Disable strict host key checking
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory on the server
scp $SCP_OPTIONS -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"


