#!/usr/bin/env bash
# pings an ip-address five times

if [ -z "$1" ]; then
    echo "Usage: $(basename "$0") {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

# Check if the IP address is valid
if ! [[ $ip_address =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: Invalid IP address format."
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$ip_address"

