#!/usr/bin/env bash
# Get the PIDs of processes whose name contains the word "bash"

pids=$(pgrep -f bash)
for pid in $pids;
do
    process_name=$(ps -p $pid -o comm=)
    echo "$pid $process_name"
done
