#!/usr/bin/env bash
# Find the process ID (PID) of the "4-to_infinity_and_beyond" process

pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -z "$pid" ]
then
  echo "Process '4-to_infinity_and_beyond' is not running."
else
  # Send SIGTERM signal to the process
  kill -15 "$pid"
fi
